### PR TITLE
Feature: Support reports on demand

### PR DESCRIPTION
**Pull request by rjpdasilva**
The tool currently only produces reports on a clean exit from the analyzed program, which is not always achievable (daemons, programs crashing, etc.). An "on demand" report requested programmatically from within the application itself or from the "outside world" via a signal, has proven quite useful in multiple debugging scenarios.

Commit 4acca12450a5 allows requesting reports via a new API function named `hu_report()`.
Commit 2de0126ce0c0 allows requesting reports via `SIGUSR1` Linux signals.
Commit 3d60e08c3dae fixes `log_summary()` so that can be called multiple times while the program is running.

### CODE REVIEW

**Comment by d99kris** [comment]
Hi @rjpdasilva - thanks for contributing 👍 
At a quick glance I think the proposed changes look good! I will need to review a bit more in detail and test a little before merging. I'm going on vacation so it may take a week or two before I get to it.

Btw - do not worry about the failing macOS check for the PR, I suspect it's some general issue caused by changes to Github CI runners, so it's something I will address separately from this PR.

**Comment by d99kris** [comment]
Hi @rjpdasilva - I've raised a [PR](https://github.com/rjpdasilva/heapusage/pull/1/files) for updating your fork with latest heapusage master so it will be easier for me to test it out.

**Comment by rjpdasilva** [comment]
Hi @d99kris,

> Hi @rjpdasilva - I've raised a [PR](https://github.com/rjpdasilva/heapusage/pull/1/files) for updating your fork with latest heapusage master so it will be easier for me to test it out.

If you prefer I can raise a new PR rebased on your latest `master`, no problem.

**Comment by d99kris** [comment]
Sure that's fine too, either works for me.

**Comment by rjpdasilva** [comment]
Hi @d99kris,

> Sure that's fine too, either works for me.

Done in #14.

**Pull request closed without merging**
