### PR TITLE
Adding a C++ example + improving CMake

### PR DESCRIPTION
**Pull request by romintomasetti**
This merge request brings the following:

* one additional test covering ``C++``

* some CMake improvements

* a new way to check the success of a test by comparing to expected output

### CODE REVIEW

**Comment by d99kris** [comment]
Hi @romintomasetti - thanks for the contribution, the CMake runtest script looks very promising! 👍 

The CI test unfortunately failed on Mac so I cannot merge this as-is. Not sure if you have a Mac and can troubleshoot? Otherwise I'll look into it when I have time. Potentially I'll merge the CMake stuff first, and not activate the cpp test to start with.

**Comment by romintomasetti** [comment]
I tried experimenting with other C++ objects, and even on Linux it sometimes fails tracking all the allocations/deallocations. Not sure if we can make it work for C++ in any generic case...

**Comment by d99kris** [comment]
Hi again @romintomasetti - I finally had some more time for this.

I found an issue in heapusage which was addressed in #5 that could cause problems in recent OS releases.

After fixing that I added your cpp test as part of #6 - however the cmake test handling was not added.

I will proceed to close this PR first, but feel free to submit a new pull request with the cmake changes if you'd like to see them merged. 

Thanks again for your contribution and sorry this PR could not be merged as-is.

**Comment by romintomasetti** [comment]
Hi @d99kris ! So, as I understand it, the ``c++`` test passes on Mac now ? That's good news !

I'll have a look a new ``c++`` examples, because my project is more ``c++``-ish so it would be great to ensure ``c++`` is supported as much / as deep as possible.

I'll also update this PR to take into account your changes :smile:

**Comment by d99kris** [comment]
Hi @romintomasetti - yes, your c++ test passes now. 👍 

I also tested heapusage on some large applications (some written in c and some in c++) and found it's working ok (tested in ubuntu and macos). 

Yes please let me know if you find more issues. 👍 
Thanks!

**Comment by d99kris** [comment]
To clarify: the c++ passes in terms of correct information reported. I only added it with simple checks on its output, but I manually saw it reported what seemed to be correct.

**Pull request closed without merging**
